#!/bin/bash
find components/chat components/forms -type f -name "*.tsx" -exec sed -i 's/bg-\[#09090b\]/bg-surface-alt/g' {} +
find components/chat components/forms -type f -name "*.tsx" -exec sed -i 's/bg-\[#121214\]/bg-surface-main/g' {} +
find components/chat components/forms -type f -name "*.tsx" -exec sed -i 's/bg-black\/40/bg-surface-alt\/40/g' {} +
find components/chat components/forms -type f -name "*.tsx" -exec sed -i 's/bg-black\/20/bg-surface-alt\/20/g' {} +
find components/chat components/forms -type f -name "*.tsx" -exec sed -i 's/bg-white\/\[0\.02\]/bg-surface-alt\/20/g' {} +
find components/chat components/forms -type f -name "*.tsx" -exec sed -i 's/bg-white\/\[0\.03\]/bg-surface-main\/40/g' {} +
find components/chat components/forms -type f -name "*.tsx" -exec sed -i 's/bg-white\/5/bg-surface-highlight/g' {} +
find components/chat components/forms -type f -name "*.tsx" -exec sed -i 's/bg-white\/10/bg-surface-alt\/80/g' {} +
find components/chat components/forms -type f -name "*.tsx" -exec sed -i 's/bg-slate-950\/60/bg-surface-main\/60/g' {} +
find components/chat components/forms -type f -name "*.tsx" -exec sed -i 's/bg-slate-950\/80/bg-surface-main\/80/g' {} +
find components/chat components/forms -type f -name "*.tsx" -exec sed -i 's/bg-slate-950/bg-surface-main/g' {} +
find components/chat components/forms -type f -name "*.tsx" -exec sed -i 's/bg-slate-900\/95/bg-surface-alt\/95/g' {} +
find components/chat components/forms -type f -name "*.tsx" -exec sed -i 's/bg-slate-800/bg-surface-main\/80/g' {} +
find components/chat components/forms -type f -name "*.tsx" -exec sed -i 's/border-white\/5/border-border-subtle/g' {} +
find components/chat components/forms -type f -name "*.tsx" -exec sed -i 's/border-white\/10/border-border-subtle/g' {} +
find components/chat components/forms -type f -name "*.tsx" -exec sed -i 's/border-white\/20/border-border-strong/g' {} +
find components/chat components/forms -type f -name "*.tsx" -exec sed -i 's/border-slate-800/border-border-subtle/g' {} +
find components/chat components/forms -type f -name "*.tsx" -exec sed -i 's/text-slate-300/text-text-primary/g' {} +
find components/chat components/forms -type f -name "*.tsx" -exec sed -i 's/text-white\/90/text-text-primary/g' {} +
find components/chat components/forms -type f -name "*.tsx" -exec sed -i 's/text-white\/40/text-text-muted/g' {} +
find components/chat components/forms -type f -name "*.tsx" -exec sed -i 's/text-white/text-text-primary/g' {} +
find components/chat components/forms -type f -name "*.tsx" -exec sed -i 's/text-zinc-500/text-text-muted/g' {} +
find components/chat components/forms -type f -name "*.tsx" -exec sed -i 's/text-zinc-300/text-text-secondary/g' {} +
find components/chat components/forms -type f -name "*.tsx" -exec sed -i 's/text-slate-400/text-text-muted/g' {} +
find components/chat components/forms -type f -name "*.tsx" -exec sed -i 's/text-slate-500/text-text-muted/g' {} +
find components/chat components/forms -type f -name "*.tsx" -exec sed -i 's/text-slate-200/text-text-secondary/g' {} +
