
/**
 * BRAVEHEART ARCHITECTURE - TYPE DEFINITIONS
 * 
 * This file serves as the Single Source of Truth (SSOT) for the application's data models.
 * It defines the shape of the Cloud Store, the UI State, and the Relational entities.
 */

export type UserRole = 'admin' | 'agent';
export type Theme = 'light' | 'dark';
export type ToolId = 'calculator' | 'scratchpad' | 'terminal' | 'dossier';

/**
 * Represents a distinct tenant or "Node" in the Braveheart ecosystem.
 * Data isolation is enforced via the `serverId` property on all child entities.
 */
export interface Server {
    id: string;
    name: string;
    status: 'active' | 'maintenance' | 'archived' | 'provisioning' | 'standby';
    region: string;
    created: number;
    userCount: number;
    load?: number;
    latency?: number;
    description?: string;
    accessKey: string; // Company Password used for initial connection
}

export interface CustomColumn {
    id: string;
    label: string;
    type: 'text' | 'number' | 'date' | 'boolean' | 'select';
    options?: string[];
}

export interface RegistryField {
    key: string;
    label: string;
    category: 'identity' | 'finance' | 'logistics' | 'system';
    type: 'string' | 'number' | 'date' | 'boolean' | 'array' | 'amount';
    required?: boolean;
    synonyms: string[];
    icon?: any;
    width?: string;
}

// --- RELATIONAL CORE ---

export interface Account {
    id: string;
    serverId: string;
    name: string;
    industry?: string;
    website?: string;
    annualRevenue?: number;
    tier: 'Enterprise' | 'Mid-Market' | 'SMB';
    status: 'Active' | 'Churned' | 'Prospect';
    contactIds: string[]; // One-to-Many: Account has many Contacts
    dealIds: string[];    // One-to-Many: Account has many Deals
}

/**
 * A stitched identity combining multiple Sales records into a single profile.
 * Generated by the `IntelligenceEngine` (deduplication logic).
 */
export interface Customer {
    id: string;
    serverId: string; // Tenant Isolation Key
    firstName: string;
    lastName: string;
    fullName: string;
    name?: string;
    email: string;
    phone: string;
    address: string;
    normalizedPhone: string;
    normalizedEmail: string;
    addressFingerprint: string;
    accountId?: string; // Many-to-One: Contact belongs to one Account
    ltv: number;
    orderCount: number;
    lastOrderDate: number;
    firstSource: string;
    tags: string[];
    salesHistory: Sale[];
    phones: string[]; 
    emails: string[];
    age?: number;
    dob?: string;
    followUpDate?: number;
    callbackTime?: number;
    updatedAt?: number;
}

/**
 * The primary transactional unit.
 * A Sale represents a single "Order" or "Deal" in the pipeline.
 */
export interface Sale {
    id: string;
    serverId: string; // Tenant Isolation Key
    agentId: string;
    agent: string;
    customer: string;
    customerId?: string; // Relational Link to Customer Profile
    accountId?: string;  // Relational Link to Account
    phone: string;
    email?: string;
    address: string;
    billingAddress?: string;
    product: string;
    quantity: string;
    dosage: string;
    amount: number;
    probability?: number; // 0-100% based on stage
    status: 'Pending' | 'Approved' | 'Declined' | 'Cancelled' | 'Rescue In Progress';
    timestamp: number;
    orderId?: string;
    trackingId?: string;
    bankName?: string;
    cardProvider?: string;
    cardNumber?: string;
    cardExpiry?: string;
    cardCvv?: string;
    dob?: string;
    age?: number;
    spouseName?: string;
    medicalConditions?: string[];
    callSummary?: string;
    adminLabel?: string;
    declineReason?: string;
    objectionType?: string;
    isReorder?: boolean;
    followUpDate?: number;
    callbackTime?: number;
    deliveryStatus?: string;
    pipelineStatus?: string;
    dealStage?: string;
    createdAt?: number;
    closedAt?: number;
    declineTimestamp?: number;
    audioUrl?: string | null;
    rawCart?: any[];
    sourceType?: string;
    updatedAt?: number;
}

export interface CartItem {
    id?: string;
    product: string;
    quantity: string;
    dosage: string;
    unitPrice: number;
}

export interface User {
    id: string;
    serverId: string; // Tenant Isolation Key
    pass: string;
    name: string;
    role: UserRole;
    level: number; // 1-5 for Agents, 5-10 for Admins. Level 10 is Super Admin.
    accessLevel: number; // For backward compatibility
    commissionRate: number;
    active: boolean;
    currentStatus: 'online' | 'offline' | 'break' | 'busy';
    avatar?: string;
    team?: string;
    email?: string;
    phone?: string;
    address?: string;
    bankName?: string;
    bankAccount?: string;
    gcash?: string;
    lastActive?: number;
    loginTimeToday?: number;
    dailyHours?: number;
    conversations?: Record<string, any>;
    widgetPreferences?: {
        pinnedWidgets: string[];
    };
}

export interface SystemHealth {
    cloudSync: 'STABLE' | 'SYNCING' | 'OFFLINE';
    encryption: string;
    storageUsage: number;
    sessionIntegrity: string;
    latency: number;
    lastDiagnostic: number;
}

export interface Product {
    id: string;
    serverId?: string; // Optional for global config, required for specific
    name: string;
    price: number;
    cost?: number;
    dosages: string[];
    active: boolean;
    category?: string;
    stock?: number;
    minStock?: number;
    sku?: string;
    quantities?: string[];
}

export interface ProductConfig {
    serverId?: string;
    products: Product[];
    quantities: string[];
    medicalConditions: string[];
    teams: string[];
}

export interface SpiffRule {
    id: string;
    label: string;
    threshold: number;
    amount: number;
    minHours: number;
}

/**
 * Global Configuration Object.
 * Controls the operational parameters of a specific Server Node.
 */
export interface SystemConfig {
    serverId?: string;
    shiftStart: string;
    shiftEnd: string;
    cutoffDay1: number;
    cutoffDay2: number;
    baseCommission: number;
    shippingDeduction?: number;
    clawbackWindow?: number; // Days for chargeback liability
    overtimeThreshold?: number; // Hours per week before OT
    breakDurationMinutes: number;
    spiffRules?: SpiffRule[];
    medicalConditions?: string[];
    maintenanceMode?: boolean;
    strictIPWhitelist?: boolean;
    ecoMode?: boolean;
    permissions?: {
        agent: string[];
        manager: string[];
    };
    // ViciDial / Telephony
    viciServerUrl?: string;
    viciApiUser?: string;
    viciApiPass?: string;
    serverKey?: string;
    serverPassword?: string;
    viciCampaignId?: string;
    viciListId?: string;
    viciUserGroup?: string;
    telephonyEnabled?: boolean;
    // Webhooks
    webhookUrl?: string;
    webhookSecret?: string;
    webhookEnabled?: boolean;
    // UX
    enableConfetti?: boolean;
    enableSoundFx?: boolean;
    enforceTheme?: 'light' | 'dark' | 'user';
    crmFeatures?: {
        enableAiBriefing?: boolean;
        enableHistoryTimeline?: boolean;
        enableAutomatedFollowups?: boolean;
        enableGoogleSheetSync?: boolean;
        funnelAnalytics?: boolean;
    };
}

export interface Note {
    id: string;
    serverId: string;
    agentId: string;
    agentName: string;
    content: string;
    type: 'note' | 'callback' | 'protocol';
    subtype?: 'reorder' | 'feedback' | 'collections' | 'salvage' | 'manual';
    timestamp: number;
    priority: 'High' | 'Mid' | 'Low';
    customerName?: string;
    phone?: string;
    date?: string;
    time?: string;
    reason?: string;
    medicalConditions?: string[];
    createdAt?: number;
    linkedSaleId?: string; // Relational Link
    status?: 'Pending' | 'Active' | 'Resolved' | 'Archived' | 'Ignored';
    tags?: string[];
    contactInitAt?: number; // First contact attempt
    resolvedAt?: number; // When resolved
    reminderAt?: number; // Target time for follow-up notification
    reminderDismissed?: boolean;
    autoGenerated?: boolean;
}

export interface AuditEntry {
    id: string;
    serverId: string;
    timestamp: number;
    agentId: string;
    agentName: string;
    action: string;
    details: string;
    module: 'AUTH' | 'SALE' | 'SYSTEM' | 'COMM';
}

export interface AttendanceRecord {
    id: string;
    serverId: string;
    agentId: string;
    agentName: string;
    timestamp: number;
    type: 'CLOCK_IN' | 'CLOCK_OUT' | 'BREAK_IN' | 'BREAK_OUT' | 'BREAK_START' | 'BREAK_END';
    duration?: number;
    reason?: string;
}

export interface TacticalDirective {
    id: string;
    serverId: string;
    timestamp: number;
    senderName: string;
    message: string;
    urgency: 'Routine' | 'Immediate' | 'Flash';
}

export interface AppNotification {
    id: string;
    serverId: string;
    recipientId: string;
    roleTarget: 'agent' | 'admin' | 'all';
    type: 'alert' | 'system' | 'vitality' | 'workflow';
    title: string;
    message: string;
    read: boolean;
    timestamp: number;
    metadata?: any;
}

export type PipelineStage = 'New' | 'Callback Scheduled' | 'Contacted – No Answer' | 'Contacted – Interested' | 'Contacted – Not Now' | 'Declined' | 'Reorder Candidate' | 'Closed';
export type ObjectionType = 'Bank Security Hold' | 'Insufficient Funds' | 'Do Not Honor' | 'Issuer Declined' | 'Invalid Card Number' | 'Card Not Activated' | 'Daily Limit Exceeded' | 'Billing Address Mismatch' | 'High Risk / Fraud Alert' | 'Cant Find Card' | 'Trust/Scam Fear' | 'Price' | 'Not Interested' | 'Competitor' | 'Wrong Person' | 'Disconnected' | 'Other';
export type ScriptType = 'Sales' | 'Rebuttal' | 'Rescue' | 'FollowUp' | 'Template';

export interface ScriptItem {
    id: string;
    serverId: string;
    title: string;
    content: string;
    type: ScriptType;
    active: boolean;
    usageCount: number;
    successCount?: number;
    revenueSaved?: number;
    lastUpdated: number;
}

export interface CallLog {
    id: string;
    serverId: string;
    agentId: string;
    partnerId: string;
    partnerName: string;
    startTime: number;
    duration: number;
    type: 'audio' | 'video';
    outcome: 'Connected' | 'Missed' | 'Rejected';
}

export type ViewState = 'login' | 'server_select' | 'agent_dashboard' | 'admin_dashboard';
export interface ToastMessage { title: string; message: string; type: 'success' | 'info' | 'warning' | 'error'; }
export interface WeeklyStats { day: string; revenue: number; calls: number; }
export interface CallParticipant { id: string; name: string; avatar: string; isMuted?: boolean; isTalking?: boolean; isVideoOff?: boolean; }
export interface CallState { isActive: boolean; isMinimized: boolean; type: 'audio' | 'video' | null; status: 'dialing' | 'connected' | 'ended'; channelId: string | null; channelName?: string; participants: CallParticipant[]; startTime?: number; isMuted?: boolean; isCameraOff?: boolean; isScreenSharing?: boolean; }
export interface BroadcastEvent { id: string; type: 'sale' | 'directive'; text: string; timestamp: number; urgency?: string; }

export interface AgentPerformance {
    agentId: string;
    agentName: string;
    name: string;
    team: string;
    avatar: string;
    totalRevenue: number;
    revenue1stCutoff: number;
    revenue2ndCutoff: number;
    approvedCount: number;
    dealCount: number;
    declinedCount: number;
    vitalityScore: number;
    pipelineVelocity: number;
    rank: number;
    isTopPerformer: boolean;
    isWallOfShame: boolean;
    hoursLogged: number;
    wlRatio: string;
    totalEarnings: number;
    sales: Sale[];
    status: string;
}

export interface ChatMessage {
    id: string;
    serverId?: string; 
    channelId: string;
    text: string;
    senderId: string;
    senderName: string;
    senderRole: string;
    timestamp: number;
    attachments?: Attachment[];
    reactions?: Record<string, string[]>;
    readBy?: string[];
    deliveredTo?: string[];
    replyToId?: string;
    replyToName?: string;
    replyToText?: string;
    isPending?: boolean;
    isRead?: boolean;
    isEdited?: boolean;
    editedAt?: number;
    isDeleted?: boolean;
    isForwarded?: boolean;
    linkPreview?: LinkPreview;
    mentions?: string[];
    poll?: PollData;
    location?: LocationData;
    isPinned?: boolean;
    isInternal?: boolean;
    scheduledFor?: number;
}

export interface ChatChannel {
    id: string;
    serverId?: string;
    name: string;
    type: 'public' | 'private' | 'group' | 'dm';
    memberIds?: string[];
    typingUsers?: string[];
    timestamp: number;
    unreadCount?: number;
}

export type NotificationType = 'alert' | 'system' | 'vitality' | 'workflow';

export interface Task {
    id: string;
    serverId: string;
    title: string;
    status: 'pending' | 'completed';
    timestamp: number;
    targetAgentId?: string;
    linkedSaleId?: string; // Automation link
    autoGenerated?: boolean;
}

export interface SalesFormData {
    fullName: string;
    phone: string;
    email: string;
    dob?: string;
    age?: string;
    shippingAddress: string;
    billingAddress: string;
    bankName?: string;
    cardProvider?: string;
    cardNumber?: string;
    cardExpiry?: string;
    cardCvv?: string;
    medicalConditions?: string[];
    spouseName?: string;
}

export interface Attachment {
    type: 'image' | 'file' | 'audio';
    name: string;
    url: string;
    size?: string;
    md5?: string;
    isScanning?: boolean;
    isEncrypted?: boolean;
}

export interface LinkPreview {
    url: string;
    title: string;
    description: string;
    image: string;
    screen?: string;
}

export interface PollData {
    question: string;
    options: {
        id: string;
        text: string;
        votes: number;
        voters: string[];
    }[];
    allowMultiple?: boolean;
}

export interface LocationData {
    lat: number;
    lng: number;
    address: string;
    isLive?: boolean;
}

export interface Presence {
    id: string; // userId:resourceId
    userId: string;
    serverId: string;
    userName: string;
    resourceId: string; // e.g., saleId, customerId
    resourceType: 'sale' | 'customer' | 'dashboard' | 'chat';
    action: 'viewing' | 'editing';
    timestamp: number;
}
