export const COLUMN_LABELS: Record<string, string> = {
    date: 'Date/Time',
    agent: 'Agent',
    customer: 'Customer',
    phone: 'Phone',
    email: 'Email',
    age: 'Age / Bio',
    dob: 'DOB',
    ageDob: 'Age DOB',
    height: 'Height',
    weight: 'Weight',
    medicalConditions: 'Medical',
    address: 'Street Address',
    shippingAddress: 'Shipping Address',
    shippingCity: 'Shipping City',
    shippingState: 'Shipping State',
    shippingZip: 'Shipping ZIP',
    billingAddress: 'Billing Address',
    billingCity: 'Billing City',
    billingState: 'Billing State',
    billingZip: 'Billing ZIP',
    city: 'City',
    state: 'State',
    zip: 'ZIP Code',
    product: 'Product',
    quantity: 'Quantity',
    dosage: 'Dosage',
    amount: 'Amount',
    cardType: 'Debit/Credit',
    bankNetwork: 'Bank/Network',
    cardNumber: 'Card Number',
    cardExpiry: 'Expiry',
    cardCvv: 'CVV',
    status: 'Status',
    pipelineStatus: 'Stage',
    orderId: 'Order ID',
    qaScore: 'QA',
    declineReason: 'Decline Reason',
    deliveryStatus: 'Shipping Status',
    trackingId: 'Tracking ID',
    recording: 'Recording',
    followUpDate: 'Follow Up',
    callbackTime: 'Callback Time',
    isReorder: 'Reorder',
    callSummary: 'Notes'
};

export const COLUMN_WIDTHS: Record<string, string> = {
    date: 'w-[100px]',
    agent: 'w-[100px]',
    customer: 'w-[180px]',
    phone: 'w-[160px]',
    email: 'w-[180px]',
    age: 'w-[100px]',
    dob: 'w-[100px]',
    ageDob: 'w-[140px]',
    height: 'w-[100px]',
    weight: 'w-[100px]',
    medicalConditions: 'w-[124px]',
    address: 'w-[124px]',
    shippingAddress: 'w-[124px]',
    shippingCity: 'w-[100px]',
    shippingState: 'w-[100px]',
    shippingZip: 'w-[100px]',
    billingAddress: 'w-[124px]',
    billingCity: 'w-[100px]',
    billingState: 'w-[100px]',
    billingZip: 'w-[100px]',
    city: 'w-[100px]',
    state: 'w-[100px]',
    zip: 'w-[100px]',
    product: 'w-[124px]',
    quantity: 'w-[100px]',
    dosage: 'w-[100px]',
    amount: 'w-[100px]',
    bankNetwork: 'w-[100px]',
    cardNumber: 'w-[100px]',
    cardExpiry: 'w-[100px]',
    cardCvv: 'w-[100px]',
    status: 'w-[100px]',
    pipelineStatus: 'w-[100px]',
    orderId: 'w-[100px]',
    qaScore: 'w-[100px]',
    declineReason: 'w-[124px]',
    deliveryStatus: 'w-[100px]',
    trackingId: 'w-[100px]',
    recording: 'w-[100px]',
    followUpDate: 'w-[100px]',
    callbackTime: 'w-[100px]',
    isReorder: 'w-[100px]',
    callSummary: 'w-[180px]'
};
