
import { Note, Sale, User } from '../types';
import { nexusGateway } from '../nexus/adapters/DataGateway';

/**
 * LEAD PROTOCOL SERVICE
 * 
 * Automatically generates follow-up nodes and reminders based on operational events.
 * This ensures no lead gets "cold" and maximizes LTV (Life Time Value).
 */

export const triggerPostSaleProtocol = async (sale: Sale, agent: User) => {
    const protocols: Partial<Note>[] = [];
    const now = Date.now();

    // 1. Approved Sale -> Feedback Protocol
    if (sale.status === 'Approved') {
        protocols.push({
            agentId: agent.id,
            agentName: agent.name,
            customerName: sale.customer,
            phone: sale.phone,
            type: 'protocol',
            subtype: 'feedback',
            content: `Quality Assurance: Check if ${sale.customer} received their ${sale.product} and is satisfied.`,
            priority: 'Mid',
            reminderAt: now + (48 * 60 * 60 * 1000), // 48 Hours Later
            status: 'Pending',
            linkedSaleId: sale.id,
            autoGenerated: true
        });

        // 2. Approved Sale -> Reorder Protocol (30 days)
        protocols.push({
            agentId: agent.id,
            agentName: agent.name,
            customerName: sale.customer,
            phone: sale.phone,
            type: 'protocol',
            subtype: 'reorder',
            content: `Replenishment Cycle: ${sale.customer}'s supply of ${sale.product} is running low. Initiate reorder.`,
            priority: 'High',
            reminderAt: now + (25 * 24 * 60 * 60 * 1000), // 25 Days Later
            status: 'Pending',
            linkedSaleId: sale.id,
            autoGenerated: true
        });
    }

    // 3. Declined Sale -> Callback Protocol
    if (sale.status === 'Declined') {
        protocols.push({
            agentId: agent.id,
            agentName: agent.name,
            customerName: sale.customer,
            phone: sale.phone,
            type: 'callback',
            subtype: 'salvage',
            content: `Salvage Operation: Attempt to rescue declined order for ${sale.customer}. Reason: ${sale.declineReason || 'Unknown'}.`,
            priority: 'High',
            reminderAt: now + (24 * 60 * 60 * 1000), // 24 Hours Later
            status: 'Pending',
            linkedSaleId: sale.id,
            autoGenerated: true
        });
    }

    // Execute Protocols
    for (const p of protocols) {
        await nexusGateway.add('notes', p);
    }
};

export const triggerLeadStagnationProtocol = async (note: Note) => {
    // If a callback was pending for more than 4 hours without resolution
    if (note.type === 'callback' && note.status === 'Pending' && !note.content.includes('STAGNATION ALERT')) {
        const threshold = 4 * 60 * 60 * 1000;
        const timePassed = Date.now() - (note.reminderAt || note.timestamp);
        
        if (timePassed > threshold) {
            // Escalate priority and update content
            await nexusGateway.update('notes', note.id!, { 
                priority: 'High', 
                content: `STAGNATION ALERT: This lead has been cold for ${Math.round(timePassed / 3600000)}h. Engage immediately. Original: ${note.content}` 
            });
            return true;
        }
    }
    return false;
};
