export const areaCodeData: Record<string, { city?: string, state: string, timezone: string }> = {
  "201": { city: "Jersey City", state: "NJ", timezone: "America/New_York" },
  "202": { city: "Washington", state: "DC", timezone: "America/New_York" },
  "203": { city: "Bridgeport", state: "CT", timezone: "America/New_York" },
  "205": { city: "Birmingham", state: "AL", timezone: "America/Chicago" },
  "206": { city: "Seattle", state: "WA", timezone: "America/Los_Angeles" },
  "208": { city: "Boise", state: "ID", timezone: "America/Boise" },
  "209": { city: "Stockton", state: "CA", timezone: "America/Los_Angeles" },
  "210": { city: "San Antonio", state: "TX", timezone: "America/Chicago" },
  "212": { city: "New York", state: "NY", timezone: "America/New_York" },
  "213": { city: "Los Angeles", state: "CA", timezone: "America/Los_Angeles" },
  "214": { city: "Dallas", state: "TX", timezone: "America/Chicago" },
  "215": { city: "Philadelphia", state: "PA", timezone: "America/New_York" },
  "216": { city: "Cleveland", state: "OH", timezone: "America/New_York" },
  "217": { city: "Springfield", state: "IL", timezone: "America/Chicago" },
  "218": { city: "Duluth", state: "MN", timezone: "America/Chicago" },
  "219": { city: "Hammond", state: "IN", timezone: "America/Chicago" },
  "220": { city: "Newark", state: "OH", timezone: "America/New_York" },
  "224": { city: "Elgin", state: "IL", timezone: "America/Chicago" },
  "225": { city: "Baton Rouge", state: "LA", timezone: "America/Chicago" },
  "228": { city: "Gulfport", state: "MS", timezone: "America/Chicago" },
  "229": { city: "Albany", state: "GA", timezone: "America/New_York" },
  "231": { city: "Muskegon", state: "MI", timezone: "America/New_York" },
  "234": { city: "Akron", state: "OH", timezone: "America/New_York" },
  "239": { city: "Cape Coral", state: "FL", timezone: "America/New_York" },
  "240": { city: "Germantown", state: "MD", timezone: "America/New_York" },
  "248": { city: "Troy", state: "MI", timezone: "America/New_York" },
  "251": { city: "Mobile", state: "AL", timezone: "America/Chicago" },
  "252": { city: "Greenville", state: "NC", timezone: "America/New_York" },
  "253": { city: "Tacoma", state: "WA", timezone: "America/Los_Angeles" },
  "254": { city: "Killeen", state: "TX", timezone: "America/Chicago" },
  "256": { city: "Huntsville", state: "AL", timezone: "America/Chicago" },
  "260": { city: "Fort Wayne", state: "IN", timezone: "America/Indiana/Indianapolis" },
  "262": { city: "Kenosha", state: "WI", timezone: "America/Chicago" },
  "267": { city: "Philadelphia", state: "PA", timezone: "America/New_York" },
  "269": { city: "Kalamazoo", state: "MI", timezone: "America/New_York" },
  "270": { city: "Bowling Green", state: "KY", timezone: "America/Chicago" },
  "281": { city: "Houston", state: "TX", timezone: "America/Chicago" },
  "301": { city: "Germantown", state: "MD", timezone: "America/New_York" },
  "302": { city: "Wilmington", state: "DE", timezone: "America/New_York" },
  "303": { city: "Denver", state: "CO", timezone: "America/Denver" },
  "304": { city: "Charleston", state: "WV", timezone: "America/New_York" },
  "305": { city: "Miami", state: "FL", timezone: "America/New_York" },
  "307": { city: "Cheyenne", state: "WY", timezone: "America/Denver" },
  "308": { city: "Grand Island", state: "NE", timezone: "America/Chicago" },
  "309": { city: "Peoria", state: "IL", timezone: "America/Chicago" },
  "310": { city: "Los Angeles", state: "CA", timezone: "America/Los_Angeles" },
  "312": { city: "Chicago", state: "IL", timezone: "America/Chicago" },
  "313": { city: "Detroit", state: "MI", timezone: "America/New_York" },
  "314": { city: "St. Louis", state: "MO", timezone: "America/Chicago" },
  "315": { city: "Syracuse", state: "NY", timezone: "America/New_York" },
  "316": { city: "Wichita", state: "KS", timezone: "America/Chicago" },
  "317": { city: "Indianapolis", state: "IN", timezone: "America/Indiana/Indianapolis" },
  "318": { city: "Shreveport", state: "LA", timezone: "America/Chicago" },
  "319": { city: "Cedar Rapids", state: "IA", timezone: "America/Chicago" },
  "320": { city: "St. Cloud", state: "MN", timezone: "America/Chicago" },
  "321": { city: "Orlando", state: "FL", timezone: "America/New_York" },
  "323": { city: "Los Angeles", state: "CA", timezone: "America/Los_Angeles" },
  "325": { city: "Abilene", state: "TX", timezone: "America/Chicago" },
  "330": { city: "Akron", state: "OH", timezone: "America/New_York" },
  "331": { city: "Aurora", state: "IL", timezone: "America/Chicago" },
  "334": { city: "Montgomery", state: "AL", timezone: "America/Chicago" },
  "336": { city: "Winston-Salem", state: "NC", timezone: "America/New_York" },
  "337": { city: "Lafayette", state: "LA", timezone: "America/Chicago" },
  "339": { city: "Malden", state: "MA", timezone: "America/New_York" },
  "346": { city: "Houston", state: "TX", timezone: "America/Chicago" },
  "347": { city: "New York", state: "NY", timezone: "America/New_York" },
  "351": { city: "Peabody", state: "MA", timezone: "America/New_York" },
  "352": { city: "Gainesville", state: "FL", timezone: "America/New_York" },
  "360": { city: "Vancouver", state: "WA", timezone: "America/Los_Angeles" },
  "361": { city: "Corpus Christi", state: "TX", timezone: "America/Chicago" },
  "364": { city: "Paducah", state: "KY", timezone: "America/Chicago" },
  "380": { city: "Columbus", state: "OH", timezone: "America/New_York" },
  "385": { city: "Salt Lake City", state: "UT", timezone: "America/Denver" },
  "386": { city: "Palm Coast", state: "FL", timezone: "America/New_York" },
  "401": { city: "Providence", state: "RI", timezone: "America/New_York" },
  "402": { city: "Omaha", state: "NE", timezone: "America/Chicago" },
  "404": { city: "Atlanta", state: "GA", timezone: "America/New_York" },
  "405": { city: "Oklahoma City", state: "OK", timezone: "America/Chicago" },
  "406": { city: "Billings", state: "MT", timezone: "America/Denver" },
  "407": { city: "Orlando", state: "FL", timezone: "America/New_York" },
  "408": { city: "San Jose", state: "CA", timezone: "America/Los_Angeles" },
  "409": { city: "Beaumont", state: "TX", timezone: "America/Chicago" },
  "410": { city: "Baltimore", state: "MD", timezone: "America/New_York" },
  "412": { city: "Pittsburgh", state: "PA", timezone: "America/New_York" },
  "413": { city: "Springfield", state: "MA", timezone: "America/New_York" },
  "414": { city: "Milwaukee", state: "WI", timezone: "America/Chicago" },
  "415": { city: "San Francisco", state: "CA", timezone: "America/Los_Angeles" },
  "417": { city: "Springfield", state: "MO", timezone: "America/Chicago" },
  "419": { city: "Toledo", state: "OH", timezone: "America/New_York" },
  "423": { city: "Chattanooga", state: "TN", timezone: "America/New_York" },
  "424": { city: "Santa Monica", state: "CA", timezone: "America/Los_Angeles" },
  "425": { city: "Bellevue", state: "WA", timezone: "America/Los_Angeles" },
  "430": { city: "Tyler", state: "TX", timezone: "America/Chicago" },
  "432": { city: "Midland", state: "TX", timezone: "America/Chicago" },
  "434": { city: "Lynchburg", state: "VA", timezone: "America/New_York" },
  "435": { city: "St. George", state: "UT", timezone: "America/Denver" },
  "440": { city: "Parma", state: "OH", timezone: "America/New_York" },
  "442": { city: "Oceanside", state: "CA", timezone: "America/Los_Angeles" },
  "443": { city: "Baltimore", state: "MD", timezone: "America/New_York" },
  "458": { city: "Eugene", state: "OR", timezone: "America/Los_Angeles" },
  "469": { city: "Dallas", state: "TX", timezone: "America/Chicago" },
  "470": { city: "Atlanta", state: "GA", timezone: "America/New_York" },
  "475": { city: "Bridgeport", state: "CT", timezone: "America/New_York" },
  "478": { city: "Macon", state: "GA", timezone: "America/New_York" },
  "479": { city: "Fort Smith", state: "AR", timezone: "America/Chicago" },
  "480": { city: "Mesa", state: "AZ", timezone: "America/Phoenix" },
  "484": { city: "Allentown", state: "PA", timezone: "America/New_York" },
  "501": { city: "Little Rock", state: "AR", timezone: "America/Chicago" },
  "502": { city: "Louisville", state: "KY", timezone: "America/New_York" },
  "503": { city: "Portland", state: "OR", timezone: "America/Los_Angeles" },
  "504": { city: "New Orleans", state: "LA", timezone: "America/Chicago" },
  "505": { city: "Albuquerque", state: "NM", timezone: "America/Denver" },
  "507": { city: "Rochester", state: "MN", timezone: "America/Chicago" },
  "508": { city: "Worcester", state: "MA", timezone: "America/New_York" },
  "509": { city: "Spokane", state: "WA", timezone: "America/Los_Angeles" },
  "510": { city: "Oakland", state: "CA", timezone: "America/Los_Angeles" },
  "512": { city: "Austin", state: "TX", timezone: "America/Chicago" },
  "513": { city: "Cincinnati", state: "OH", timezone: "America/New_York" },
  "515": { city: "Des Moines", state: "IA", timezone: "America/Chicago" },
  "516": { city: "Hempstead", state: "NY", timezone: "America/New_York" },
  "517": { city: "Lansing", state: "MI", timezone: "America/New_York" },
  "518": { city: "Albany", state: "NY", timezone: "America/New_York" },
  "520": { city: "Tucson", state: "AZ", timezone: "America/Phoenix" },
  "530": { city: "Redding", state: "CA", timezone: "America/Los_Angeles" },
  "531": { city: "Omaha", state: "NE", timezone: "America/Chicago" },
  "534": { city: "Eau Claire", state: "WI", timezone: "America/Chicago" },
  "539": { city: "Tulsa", state: "OK", timezone: "America/Chicago" },
  "540": { city: "Roanoke", state: "VA", timezone: "America/New_York" },
  "541": { city: "Eugene", state: "OR", timezone: "America/Los_Angeles" },
  "551": { city: "Jersey City", state: "NJ", timezone: "America/New_York" },
  "559": { city: "Fresno", state: "CA", timezone: "America/Los_Angeles" },
  "561": { city: "West Palm Beach", state: "FL", timezone: "America/New_York" },
  "562": { city: "Long Beach", state: "CA", timezone: "America/Los_Angeles" },
  "563": { city: "Davenport", state: "IA", timezone: "America/Chicago" },
  "567": { city: "Toledo", state: "OH", timezone: "America/New_York" },
  "570": { city: "Scranton", state: "PA", timezone: "America/New_York" },
  "571": { city: "Arlington", state: "VA", timezone: "America/New_York" },
  "573": { city: "Columbia", state: "MO", timezone: "America/Chicago" },
  "574": { city: "South Bend", state: "IN", timezone: "America/Indiana/Indianapolis" },
  "580": { city: "Lawton", state: "OK", timezone: "America/Chicago" },
  "585": { city: "Rochester", state: "NY", timezone: "America/New_York" },
  "586": { city: "Warren", state: "MI", timezone: "America/New_York" },
  "601": { city: "Jackson", state: "MS", timezone: "America/Chicago" },
  "602": { city: "Phoenix", state: "AZ", timezone: "America/Phoenix" },
  "603": { city: "Manchester", state: "NH", timezone: "America/New_York" },
  "605": { city: "Sioux Falls", state: "SD", timezone: "America/Chicago" },
  "606": { city: "Ashland", state: "KY", timezone: "America/New_York" },
  "607": { city: "Binghamton", state: "NY", timezone: "America/New_York" },
  "608": { city: "Madison", state: "WI", timezone: "America/Chicago" },
  "609": { city: "Trenton", state: "NJ", timezone: "America/New_York" },
  "610": { city: "Allentown", state: "PA", timezone: "America/New_York" },
  "612": { city: "Minneapolis", state: "MN", timezone: "America/Chicago" },
  "614": { city: "Columbus", state: "OH", timezone: "America/New_York" },
  "615": { city: "Nashville", state: "TN", timezone: "America/Chicago" },
  "616": { city: "Grand Rapids", state: "MI", timezone: "America/New_York" },
  "617": { city: "Boston", state: "MA", timezone: "America/New_York" },
  "618": { city: "Belleville", state: "IL", timezone: "America/Chicago" },
  "619": { city: "San Diego", state: "CA", timezone: "America/Los_Angeles" },
  "620": { city: "Hutchinson", state: "KS", timezone: "America/Chicago" },
  "623": { city: "Glendale", state: "AZ", timezone: "America/Phoenix" },
  "626": { city: "Pasadena", state: "CA", timezone: "America/Los_Angeles" },
  "630": { city: "Aurora", state: "IL", timezone: "America/Chicago" },
  "631": { city: "Brentwood", state: "NY", timezone: "America/New_York" },
  "636": { city: "O'Fallon", state: "MO", timezone: "America/Chicago" },
  "646": { city: "New York", state: "NY", timezone: "America/New_York" },
  "650": { city: "San Mateo", state: "CA", timezone: "America/Los_Angeles" },
  "651": { city: "St. Paul", state: "MN", timezone: "America/Chicago" },
  "657": { city: "Anaheim", state: "CA", timezone: "America/Los_Angeles" },
  "661": { city: "Bakersfield", state: "CA", timezone: "America/Los_Angeles" },
  "662": { city: "Southaven", state: "MS", timezone: "America/Chicago" },
  "678": { city: "Atlanta", state: "GA", timezone: "America/New_York" },
  "682": { city: "Fort Worth", state: "TX", timezone: "America/Chicago" },
  "701": { city: "Fargo", state: "ND", timezone: "America/Chicago" },
  "702": { city: "Las Vegas", state: "NV", timezone: "America/Los_Angeles" },
  "703": { city: "Arlington", state: "VA", timezone: "America/New_York" },
  "704": { city: "Charlotte", state: "NC", timezone: "America/New_York" },
  "706": { city: "Augusta", state: "GA", timezone: "America/New_York" },
  "707": { city: "Santa Rosa", state: "CA", timezone: "America/Los_Angeles" },
  "708": { city: "Cicero", state: "IL", timezone: "America/Chicago" },
  "712": { city: "Sioux City", state: "IA", timezone: "America/Chicago" },
  "713": { city: "Houston", state: "TX", timezone: "America/Chicago" },
  "714": { city: "Anaheim", state: "CA", timezone: "America/Los_Angeles" },
  "715": { city: "Eau Claire", state: "WI", timezone: "America/Chicago" },
  "716": { city: "Buffalo", state: "NY", timezone: "America/New_York" },
  "717": { city: "Lancaster", state: "PA", timezone: "America/New_York" },
  "718": { city: "New York", state: "NY", timezone: "America/New_York" },
  "719": { city: "Colorado Springs", state: "CO", timezone: "America/Denver" },
  "720": { city: "Denver", state: "CO", timezone: "America/Denver" },
  "724": { city: "New Castle", state: "PA", timezone: "America/New_York" },
  "727": { city: "St. Petersburg", state: "FL", timezone: "America/New_York" },
  "731": { city: "Jackson", state: "TN", timezone: "America/Chicago" },
  "732": { city: "Toms River", state: "NJ", timezone: "America/New_York" },
  "734": { city: "Ann Arbor", state: "MI", timezone: "America/New_York" },
  "740": { city: "Newark", state: "OH", timezone: "America/New_York" },
  "747": { city: "Los Angeles", state: "CA", timezone: "America/Los_Angeles" },
  "757": { city: "Virginia Beach", state: "VA", timezone: "America/New_York" },
  "760": { city: "Oceanside", state: "CA", timezone: "America/Los_Angeles" },
  "762": { city: "Augusta", state: "GA", timezone: "America/New_York" },
  "763": { city: "Brooklyn Park", state: "MN", timezone: "America/Chicago" },
  "765": { city: "Muncie", state: "IN", timezone: "America/Indiana/Indianapolis" },
  "770": { city: "Roswell", state: "GA", timezone: "America/New_York" },
  "772": { city: "Port St. Lucie", state: "FL", timezone: "America/New_York" },
  "773": { city: "Chicago", state: "IL", timezone: "America/Chicago" },
  "774": { city: "Worcester", state: "MA", timezone: "America/New_York" },
  "775": { city: "Reno", state: "NV", timezone: "America/Los_Angeles" },
  "781": { city: "Waltham", state: "MA", timezone: "America/New_York" },
  "785": { city: "Topeka", state: "KS", timezone: "America/Chicago" },
  "786": { city: "Miami", state: "FL", timezone: "America/New_York" },
  "801": { city: "Salt Lake City", state: "UT", timezone: "America/Denver" },
  "802": { city: "Burlington", state: "VT", timezone: "America/New_York" },
  "803": { city: "Columbia", state: "SC", timezone: "America/New_York" },
  "804": { city: "Richmond", state: "VA", timezone: "America/New_York" },
  "805": { city: "Oxnard", state: "CA", timezone: "America/Los_Angeles" },
  "806": { city: "Lubbock", state: "TX", timezone: "America/Chicago" },
  "810": { city: "Flint", state: "MI", timezone: "America/New_York" },
  "812": { city: "Evansville", state: "IN", timezone: "America/Chicago" },
  "813": { city: "Tampa", state: "FL", timezone: "America/New_York" },
  "814": { city: "Erie", state: "PA", timezone: "America/New_York" },
  "815": { city: "Rockford", state: "IL", timezone: "America/Chicago" },
  "816": { city: "Kansas City", state: "MO", timezone: "America/Chicago" },
  "817": { city: "Fort Worth", state: "TX", timezone: "America/Chicago" },
  "818": { city: "Los Angeles", state: "CA", timezone: "America/Los_Angeles" },
  "828": { city: "Asheville", state: "NC", timezone: "America/New_York" },
  "830": { city: "New Braunfels", state: "TX", timezone: "America/Chicago" },
  "831": { city: "Salinas", state: "CA", timezone: "America/Los_Angeles" },
  "832": { city: "Houston", state: "TX", timezone: "America/Chicago" },
  "843": { city: "Charleston", state: "SC", timezone: "America/New_York" },
  "845": { city: "Poughkeepsie", state: "NY", timezone: "America/New_York" },
  "847": { city: "Elgin", state: "IL", timezone: "America/Chicago" },
  "850": { city: "Tallahassee", state: "FL", timezone: "America/New_York" },
  "854": { city: "Charleston", state: "SC", timezone: "America/New_York" },
  "856": { city: "Camden", state: "NJ", timezone: "America/New_York" },
  "857": { city: "Boston", state: "MA", timezone: "America/New_York" },
  "858": { city: "San Diego", state: "CA", timezone: "America/Los_Angeles" },
  "859": { city: "Lexington", state: "KY", timezone: "America/New_York" },
  "860": { city: "Hartford", state: "CT", timezone: "America/New_York" },
  "862": { city: "Newark", state: "NJ", timezone: "America/New_York" },
  "863": { city: "Lakeland", state: "FL", timezone: "America/New_York" },
  "864": { city: "Greenville", state: "SC", timezone: "America/New_York" },
  "865": { city: "Knoxville", state: "TN", timezone: "America/New_York" },
  "870": { city: "Jonesboro", state: "AR", timezone: "America/Chicago" },
  "872": { city: "Chicago", state: "IL", timezone: "America/Chicago" },
  "878": { city: "Pittsburgh", state: "PA", timezone: "America/New_York" },
  "901": { city: "Memphis", state: "TN", timezone: "America/Chicago" },
  "903": { city: "Tyler", state: "TX", timezone: "America/Chicago" },
  "904": { city: "Jacksonville", state: "FL", timezone: "America/New_York" },
  "906": { city: "Marquette", state: "MI", timezone: "America/New_York" },
  "907": { city: "Anchorage", state: "AK", timezone: "America/Anchorage" },
  "908": { city: "Elizabeth", state: "NJ", timezone: "America/New_York" },
  "909": { city: "San Bernardino", state: "CA", timezone: "America/Los_Angeles" },
  "910": { city: "Fayetteville", state: "NC", timezone: "America/New_York" },
  "912": { city: "Savannah", state: "GA", timezone: "America/New_York" },
  "913": { city: "Overland Park", state: "KS", timezone: "America/Chicago" },
  "914": { city: "Yonkers", state: "NY", timezone: "America/New_York" },
  "915": { city: "El Paso", state: "TX", timezone: "America/Denver" },
  "916": { city: "Sacramento", state: "CA", timezone: "America/Los_Angeles" },
  "917": { city: "New York", state: "NY", timezone: "America/New_York" },
  "918": { city: "Tulsa", state: "OK", timezone: "America/Chicago" },
  "919": { city: "Raleigh", state: "NC", timezone: "America/New_York" },
  "920": { city: "Green Bay", state: "WI", timezone: "America/Chicago" },
  "925": { city: "Concord", state: "CA", timezone: "America/Los_Angeles" },
  "928": { city: "Yuma", state: "AZ", timezone: "America/Phoenix" },
  "931": { city: "Clarksville", state: "TN", timezone: "America/Chicago" },
  "936": { city: "Conroe", state: "TX", timezone: "America/Chicago" },
  "937": { city: "Dayton", state: "OH", timezone: "America/New_York" },
  "938": { city: "Huntsville", state: "AL", timezone: "America/Chicago" },
  "940": { city: "Denton", state: "TX", timezone: "America/Chicago" },
  "941": { city: "Sarasota", state: "FL", timezone: "America/New_York" },
  "947": { city: "Troy", state: "MI", timezone: "America/New_York" },
  "949": { city: "Irvine", state: "CA", timezone: "America/Los_Angeles" },
  "951": { city: "Riverside", state: "CA", timezone: "America/Los_Angeles" },
  "952": { city: "Bloomington", state: "MN", timezone: "America/Chicago" },
  "954": { city: "Fort Lauderdale", state: "FL", timezone: "America/New_York" },
  "956": { city: "Laredo", state: "TX", timezone: "America/Chicago" },
  "970": { city: "Fort Collins", state: "CO", timezone: "America/Denver" },
  "971": { city: "Portland", state: "OR", timezone: "America/Los_Angeles" },
  "972": { city: "Dallas", state: "TX", timezone: "America/Chicago" },
  "973": { city: "Newark", state: "NJ", timezone: "America/New_York" },
  "978": { city: "Lowell", state: "MA", timezone: "America/New_York" },
  "979": { city: "College Station", state: "TX", timezone: "America/Chicago" },
  "980": { city: "Charlotte", state: "NC", timezone: "America/New_York" },
  "984": { city: "Raleigh", state: "NC", timezone: "America/New_York" },
  "985": { city: "Houma", state: "LA", timezone: "America/Chicago" },
  "989": { city: "Saginaw", state: "MI", timezone: "America/New_York" }
};
